#!/bin/bash

ln -s ~/.dotfiles/vim ~/.vim
ln -s ~/.dotfiles/vim/vimrc ~/.vimrc
ln -s ~/.dotfiles/gitconfig .gitconfig

echo "" >> ~/.bashrc
echo "# I Love my prompt" >> ~/.bashrc
echo "source ~/.dotfiles/bashrc.d/git-completion.bash" >> ~/.bashrc
echo "source ~/.dotfiles/bashrc.d/prompt.bash" >> ~/.bashrc

bash
