#!/bin/bash

SOURCE=$PWD"/"$BASH_SOURCE
DIR=$(dirname ${SOURCE})

## Create links
ln -s $DIR/vim ~/.vim
ln -s $DIR/vim/vimrc ~/.vimrc
ln -s $DIR/gitconfig ~/.gitconfig
ln -s $DIR/screenrc ~/.screenrc
ln -s $DIR/tmux.conf ~/.tmux.conf

## Install some packages
sudo apt-get install -y python-pip
sudo pip install jedi

##  Set bash rc
echo "" >> ~/.bashrc
echo "### I Love my prompt" >> ~/.bashrc
echo "source $DIR/bashrc.d/git-completion.bash" >> ~/.bashrc
echo "source $DIR/bashrc.d/git-prompt.bash" >> ~/.bashrc
echo "source $DIR/bashrc.d/colors.bash" >> ~/.bashrc
echo "source $DIR/bashrc.d/prompt.bash" >> ~/.bashrc
echo "" >> ~/.bashrc
echo "### Vim as default editor" >> ~/.bashrc
echo "export EDITOR=vim" >> ~/.bashrc

## Clone VIM plugins
git clone https://github.com/tomtom/tcomment_vim.git $DIR/vim/bundle/tcomment
git clone https://github.com/scrooloose/nerdtree.git $DIR/vim/bundle/nerdtree
git clone https://github.com/sukima/xmledit.git $DIR/vim/bundle/xmledit
git clone git://github.com/majutsushi/tagbar $DIR/vim/bundle/tagbar
git clone git://github.com/tpope/vim-fugitive.git $DIR/vim/bundle/vim-fugitive
git clone git://github.com/tpope/vim-surround.git $DIR/vim/bundle/vim-surround
git clone git://github.com/nvie/vim-flake8.git  $DIR/vim/bundle/vim-flake8
git clone https://github.com/bling/vim-airline.git $DIR/vim/bundle/vim-airline
git clone https://github.com/puppetlabs/puppet-syntax-vim.git $DIR/vim/bundle/puppet-syntax-vim
git clone https://github.com/jmcantrell/vim-virtualenv.git $DIR/vim/bundle/vim-virtualenv
git clone https://github.com/kien/ctrlp.vim.git $DIR/vim/bundle/ctrlp

# Snipmate needs several clones
git clone https://github.com/tomtom/tlib_vim.git $DIR/vim/bundle/tlib_vim
git clone https://github.com/MarcWeber/vim-addon-mw-utils.git $DIR/vim/bundle/vim-addon-mw-utils
git clone --recursive https://github.com/davidhalter/jedi-vim.git $DIR/vim/bundle/jedi-vim
git clone https://github.com/honza/vim-snippets.git $DIR/vim/bundle/vim-snippets

source $HOME/.bashrc
