#!/bin/bash

## Create links
ln -s ~/.dotfiles/vim ~/.vim
ln -s ~/.dotfiles/vim/vimrc ~/.vimrc
ln -s ~/.dotfiles/gitconfig ~/.gitconfig
ln -s ~/.dotfiles/screenrc ~/.screenrc

##  Set bash rc
echo "" >> ~/.bashrc
echo "### I Love my prompt" >> ~/.bashrc
echo "source ~/.dotfiles/bashrc.d/git-completion.bash" >> ~/.bashrc
echo "source ~/.dotfiles/bashrc.d/prompt.bash" >> ~/.bashrc
echo "" >> ~/.bashrc
echo "### Vim as default editor" >> ~/.bashrc
echo "export EDITOR=vim" >> ~/.bashrc

## Clone VIM plugins
git clone https://github.com/tomtom/tcomment_vim.git ~/.dotfiles/vim/bundle/tcomment
git clone https://github.com/scrooloose/nerdtree.git ~/.dotfiles/vim/bundle/nerdtree
git clone https://github.com/sukima/xmledit.git ~/.dotfiles/vim/bundle/xmledit
git clone git://github.com/majutsushi/tagbar ~/.dotfiles/vim/bundle/tagbar
git clone git://github.com/tpope/vim-fugitive.git ~/.dotfiles/vim/bundle/vim-fugitive
git clone git://github.com/tpope/vim-surround.git ~/.dotfiles/vim/bundle/vim-surround
git clone git://github.com/nvie/vim-flake8.git  ~/.dotfiles/vim/bundle/vim-flake8
git clone https://github.com/bling/vim-airline.git ~/.dotfiles/vim/bundle/vim-airline

bash
